In [29]:
import pandas as pd
import numpy as np

In [30]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [31]:
df = pd.read_csv('houses.csv')
df.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
130,4 Bedroom House for sale in Sector 109 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,International City by SOBHA Phase 2,6.8 Crore,"₹ 12,593/sq.ft.",(502 sq.m.) Plot Area,Plot area 600(501.68 sq.m.),4 Bedrooms,5 Bathrooms,3 Balconies,Servant Room,"128, Sector 109 Gurgaon, Gurgaon, Haryana",2 Floors,North-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",Very beautiful location and sobha internationa...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",P70106010
694,4 Bedroom House for sale in Sector 82 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Vatika India Next4.1 ★,6.8 Crore,"₹ 20,988/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"Block S, Sector 82 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka expressway', 'Del...",360 sq yard fully furnished villa is available...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5...",W69922318
700,9 Bedroom House for sale in Sector 27 Gurgaon,https://www.99acres.com/9-bhk-bedroom-independ...,NaN,8 Crore,"₹ 26,298/sq.ft.",(283 sq.m.) Plot Area,Plot area 338(282.61 sq.m.),9 Bedrooms,9 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Sector 27 Gurgaon, Gurgaon, Haryana",4 Floors,North-East,1 to 5 Year Old,"['Dlf phase 1 metro station', 'Sector 42-43 me...",Check out this 9bhk house for sale in sector 2...,"['1 Water Purifier', '9 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",R69688626
69,4 Bedroom House for sale in Sector 109 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,International City by SOBHA Phase 2,NaN,"₹ 13,910/sq.ft.",(294-418 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5...",L70075120
329,4 Bedroom House for sale in Vir Nagar,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,78 Lac,"₹ 9,725/sq.ft.",(75 sq.m.) Carpet Area,Carpet area: 802 (74.51 sq.m.),4 Bedrooms,4 Bathrooms,No Balcony,NaN,"Veer Nagar, Gurgaon, Haryana, India, Vir Nagar...",3 Floors,North-East,undefined,"['Lal Superspeciality Hospital', 'Shri Gobind ...","Indipendent house ground floor- Bed room, draw...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN,S64473956

In [32]:
# shape
df.shape

(1044, 21)

In [33]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   object
 1   link             1044 non-null   object
 2   society          453 non-null    object
 3   price            968 non-null    object
 4   rate             1005 non-null   object
 5   area             1044 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 171.4+ KB

In [34]:
# check for duplicates
df.duplicated().sum()

13

In [35]:
df.drop_duplicates(inplace=True)

In [36]:
df.shape

(1031, 21)

In [37]:
df.isnull().sum()

property_name        0
link                 0
society            586
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     453
address             13
noOfFloor           76
facing             369
agePossession       57
nearbyLocations    131
description          8
furnishDetails     299
features           369
rating             137
property_id          8
dtype: int64

In [38]:
df.drop(columns = ['link' , 'property_id'] , inplace = True)

In [39]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [40]:
df.rename(columns = {'rate':'price_per_sqft'} , inplace = True)

## society

In [41]:
df.society.value_counts()

society
International City by SOBHA Phase 2                  26
Emaar MGF Marbella                                   26
Vipul Tatvam Villa                                   24
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             13
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Unitech Espace                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Not Applicable                                        7
Uppal Southend4.0 ★                                   7
Sushant Lok 1 Builder Floors                          6
Ansals Palam Vihar                                    6
DLF City Phase 1                                      5
Experion Windchants3.8 ★                              5
DLF Alameda                                           4
Unitech Aspen Greens                                  4
Ansal Sushant Lok Plots4.1 ★                          4
Vatika India Next4.1 ★                                4
nul                                                   4
Malibu Towne                                          3
Eros Rosewood City4.0 ★                               3
Rattan Garden                                         3
Housing Board Colony                                  3
BPTP Astaire Gardens3.7 ★                             3
SS Aaron Ville                                        3
Palam Vihar Extension West Zone RWA                   3
Unitech Nirvana Birch Court                           3
Puri Diplomatic Greens4.0 ★                           3
Vatika Signature Villas                               3
Eros Rosewood Villas                                  3
DLF City Plots Phase 3                                3
Central Park Flower Valley                            3
Sector 14 RWA                                         3
DLF New Town Heights 24.0 ★                           3
Anant Raj Estates                                     3
Tata Primanti4.1 ★                                    3
Ansals Florence Villa                                 3
Sobha City                                            2
Ardee City3.8 ★                                       2
Bestech Park View Ananda4.2 ★                         2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Unitech Escape3.8 ★                                   2
SS Hibiscus                                           2
Satya The Hermitage3.5 ★                              2
Hans Enclave                                          2
Suncity Township4.1 ★                                 2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
Project Mianwali Colony                               2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Project Housing Board Colony                          2
Silverglades Tarudhan Valley Golf Resort              2
Spaze Privy3.9 ★                                      2
Suncity Essel Towers4.2 ★                             2
Luxury DLF City Floors                                2
Emaar Emerald Hills4.1 ★                              2
Ansal API Esencia3.7 ★                                2
shivpuri                                              2
Unitech Deerwood Chase                                2
Om Nagar, Sector-11                                   1
Central Park Flower Valley Cerise Floors              1
Kothi                                                 1
Birla Navya                                           1
Ansal API Spanish Court                               1
private house                                         1
4S Aradhya Homes                                      1
Sector-17C                                            1
Ireo Victory Valley4.1 ★                              1
Ansal Florence Super                                  1
Smart World Orchard                                   1
HUDA Ashok Vihar Phase 13.9 ★                         1
DLF City Plots Phase 4                                1
Ashok Vihar Phase 3 Gurgaon                           1
nirvana country                                       1
Landmark House                                        1
Farrukhnagar                                          1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal                                                 1
Ashok vihar phase III Extension                       1
Prem Kunj                                             1
rattan vihar rajendra park                            1
Signature Global City 63A                             1
Unitech South City 23.8 ★                             1
DLF Floors Phase 3                                    1
huda sector-56 gurgaon                                1
Ireo Victory Valley4.0 ★                              1
Huda Floor                                            1
Huda                                                  1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Grover Homes Sec 4                                    1
DLF Pink Town House4.0 ★                              1
FLOOR WISE DESIGNER KOTHI                             1
Satya The Legend3.8 ★                                 1
Independent House Sector 45                           1
Adani Brahma Samsara4.2 ★                             1
sector 37                                             1
DLF New Town Heights3.7 ★                             1
All Punjabi Welfare Association                       1
Unitech Greenwood City3.6 ★                           1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF South City 1                                      1
Ansal Sushant Residency                               1
DLF City Plot Phase 3                                 1
sneh vihar                                            1
DLF The Arbour                                        1
mian wali                                             1
Ansal Celebrity Homes                                 1
Laxmi Garden Sector-11                                1
HUDA Housing Board Colony4.1 ★                        1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
Surat nagar phase 2                                   1
RK Excelo                                             1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
DLF Gardencity Enclave                                1
Rajendra Park Gurgaon                                 1
house number B-34                                     1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Emaar MGF The Palm Drive4.1 ★                         1
ATS Tourmaline3.9 ★                                   1
Tulip Ivory3.5 ★                                      1
Huda Plots                                            1
Bhawani enclave                                       1
DLF Garden City Floors                                1
Shri Shyam Residency                                  1
My Home                                               1
Sheetla Enclave                                       1
HUDA Plot Sector 38                                   1
Suncity Avenue 76                                     1
SS Omnia                                              1
secter 16a daultabad faridabad house no 313           1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
rajendra park sec 105                                 1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
Shivaji Nagar Residential                             1
Bhim Nagar Society                                    1
Ansal Heights3.2 ★                                    1
Signature Global City 92                              1
DLF City Plot Phase 4                                 1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Krishna Palace                                        1
Ninex City                                            1
Huda Flats                                            1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Madan puri                                            1
Signature Global Park4.0 ★                            1
ROW HOUSE                                             1
Name: count, dtype: int64

In [42]:
df.society.isnull().sum()

586

In [43]:
df['society'].value_counts().shape

(185,)

In [14]:
import re

In [44]:
df.society = df.society.apply(lambda name : re.sub(r'\d+(\.\d+)?\s?★','' , str(name)).strip()).str.lower()

In [45]:
df['society'].value_counts().shape

(183,)

In [46]:
df.society = df['society'].str.replace('nan','independent')

In [51]:
df.price.str.split().str[1].value_counts()

price
Crore    741
Lac      204
on        10
Name: count, dtype: int64

In [52]:
df = df[df['price'] != 'Price on Request']

In [53]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [54]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [57]:
# price_per_sqft
df[~df['price_per_sqft'].str.contains('sq.ft.',na = False)]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
47,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,NaN,(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","14a, Sector 66 Gurgaon, Gurgaon, Haryana",3 Floors,East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Excellent location, 24 meter wide road facing ...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '15 L...","['Centrally Air Conditioned', 'Water purifier'...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
88,5 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(251-704 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
89,3 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(211 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
104,4 Bedroom House for sale in Sector 65 Gurgaon,emaar emerald hills,NaN,NaN,(183 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 65 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Emerald Plaza Shopping Mall', 'Southern Peri...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
105,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
115,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,NaN,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
250,6 Bedroom House for sale in Sector 11 Gurgaon,independent,NaN,NaN,(251 sq.m.) Plot Area,Plot area 2700(250.84 sq.m.),6 Bedrooms,4 Bathrooms,2 Balconies,NaN,"4/145, Sector 11 Gurgaon, Gurgaon, Haryana",2 Floors,East,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Stat...",Interested to sell independent house/villa.Pla...,"['1 Bed', '1 Wardrobe', '1 Fan', '1 Light', 'N...","['Water Storage', 'Park', 'Waste Disposal']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
273,5 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,NaN,NaN,(509-543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Metro Station Kankrola sec 87', 'Sapphire 83...","Bestech park view ananda in sector-81 gurgaon,...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
277,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
278,6 Bedroom House for sale in Sector 70 Gurgaon,tulip ivory,NaN,NaN,(697 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 70 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Reach 3 Roads Shopping Mall', 'Southern Peri...","Tulip ivory in sector-70, gurgaon by tulip inf...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
284,3 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf the palm drive,NaN,NaN,(353 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf the palm drive in sector-66, gurgaon...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
299,2 Bedroom House for sale in Shakti Nagar,independent,NaN,NaN,(93 sq.m.) Plot Area,Plot area 1000(92.9 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Shakti Nagar, Gurgaon, Haryana",1 Floors,NaN,5 to 10 Year Old,"['Lal Superspeciality Hospital', 'Shri Gobind ...","2 bath, dimensions 1000 x 500 ft, semi-Furnish...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
326,4 Bedroom House for sale in Sector 52 Gurgaon,independent,NaN,NaN,(201 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
371,5 Bedroom House for sale in Sector 108 Gurgaon,sobha city,NaN,NaN,(681 sq.m.) Built-up Area,Built Up area: 7331 (681.07 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 109, Sector 108 Gurgaon, Gurgaon, Haryana",1 Floors,NaN,10+ Year Old,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",Best in class property available at sector 109...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
436,5 Bedroom House for sale in Laxman Vihar,not applicable,NaN,NaN,(560 sq.m.) Plot Area,Plot area 670(560.21 sq.m.),5 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Laxman Vihar, Gurgaon, Haryana",3 Floors,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Prat...",I have a house/villa available for sale in sar...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
444,4 Bedroom House for sale in Udyog Vihar Phase 1,independent,NaN,NaN,(1115 sq.m.) Plot Area,Plot area 12000(1114.84 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Servant Room,Store Room","320a, Udyog Vihar Phase 1, Gurgaon, Haryana",4 Floors,North,5 to 10 Year Old,"['Indusind bank cyber city metro station', 'Mi...",1. Elevators:\nThe building has a state of the...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
462,7 Bedroom House for sale in Naharpur Rupa,independent,NaN,NaN,(42 sq.m.) Plot Area,Plot area 50(41.81 sq.m.),7 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Naharpur Rupa, Gurgaon, Haryana",2 Floors,South,10+ Year Old,"['Rajiv Chowk Mosque', 'Parmar Dental Clinic &...",Great location\n650meter from nh8\nNear by man...,NaN,['Water Storage'],"['Environment3 out of 5', 'Lifestyle3.5 out of..."
584,5 Bedroom House for sale in DLF Phase 3,dlf city plot phase 3,NaN,NaN,(465 sq.m.) Built-up Area,Built Up area: 5000 (464.52 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,NaN,"V Block, DLF Phase 3, Gurgaon, Haryana",4 Floors,North-East,undefined,NaN,"5 bath, semi-Furnished, overlooking garden/par...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
731,12 Bedroom House for sale in DLF Phase 2,independent,NaN,NaN,(209 sq.m.) Plot Area,Plot area 250(209.03 sq.m.)Built Up area: 260 ...,12 Bedrooms,12 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others","DLF Phase 2, Gurgaon, Haryana",4 Floors,North-East,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...",Its a brand new ultra luxury independent build...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
739,5 Bedroom House for sale in Sector 33 Gurgaon,unitech uniworld resorts,NaN,NaN,(435 sq.m.) Plot Area,Plot area 520(434.79 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,"Servant Room,Store Room","A-898, Sector 33 Gurgaon, Gurgaon, Haryana",4 Floors,West,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",5 bhk 520 sqyd villas available at unitech uni...,"['5 Wardrobe', '15 Fan', '1 Exhaust Fan', '5 G...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
768,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,NaN,(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),5 Bedrooms,7 Bathrooms,3+ Balconies,"Pooja Room,Store Room,Study Room,Servant Room","Md-45, Sector 66 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Property is located in very posh area, park fa...","['16 Fan', '1 Exhaust Fan', '8 Geyser', '1 Sto...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
795,5 Bedroom House for sale in Sector 33 Gurgaon,unitech uniworld resorts,NaN,NaN,(420 sq.m.) Plot Area,Plot area 502(419.74 sq.m.),5 Bedrooms,7 Bathrooms,3+ Balconies,Servant Room,"A-8, Sector 33 Gurgaon, Gurgaon, Haryana",3 Floors,South-East,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",502 sqyd 5bhk villa available for sale at unit...,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
803,16 Bedroom House for sale in DLF Phase 4,independent,NaN,NaN,(226 sq.m.) Plot Area,Plot area 270(225.75 sq.m.),16 Bedrooms,16 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others","Super Mart 2, DLF Phase 4, Gurgaon, Haryana",4 Floors,North-West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...",Independent building floor wise with stilt and...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
820,5 Bedroom House for sale in Nirvana Country,unitech espace,NaN,NaN,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,Study Room,"Nirvana Country, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",Urgent for sale villa in nirvana country\nOn w...,"['5 Wardrobe', '5 Fan', '11 Light', '6 AC', 'N...","['Maintenance Staff', 'Water Storage', 'Park',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
844,9 Bedroom House for sale in Sector 45 Gurgaon,unitech greenwood city,NaN,NaN,(201 sq.m.) Plot Area,Plot area 240(200.67 sq.m.),9 Bedrooms,9 Bathrooms,3+ Balconies,"Study Room,Servant Room","Sector 45 Gurgaon, Gurgaon, Haryana",3 Floors,South-East,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...","5 years old built up, ground + first + second,...","['1 Water Purifier', '16 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
920,5 Bedroom House for sale in DLF Phase 2,independent,NaN,NaN,(420 sq.m.) Plot Area,Plot area 502(419.74 sq.m.)Built Up area: 450 ...,5 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",2 Floors,West,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...",Dlf phase 2 very prime location. This villa we...,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1003,5 Bedroom House for sale in Sector 33 Gurgaon,unitech uniworld resorts,NaN,NaN,(435 sq.m.) Plot Area,Plot area 520(434.79 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,"Servant Room,Store Room","A-898, Sector 33 Gurgaon, Gurgaon, Haryana",4 Floors,West,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",5 bhk 520 sqyd villas available at unitech uni...,"['5 Wardrobe', '15 Fan', '1 Exhaust Fan', '5 G...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1023,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,NaN,(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.)Built Up area: 6500...,4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Sector 66 Gurgaon, Gurgaon, Haryana",3 Floors,North,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This is 350 sq.Yd villa in the heart of the ci...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1024,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,NaN,(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.),5 Bedrooms,5 Bathrooms,3 Balconies,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."

In [58]:
df.price_per_sqft.head()

0     ₹ 20,115/sq.ft.
1    ₹ 105,751/sq.ft.
2     ₹ 38,251/sq.ft.
3     ₹ 43,066/sq.ft.
4     ₹ 53,763/sq.ft.
Name: price_per_sqft, dtype: object

In [63]:
df.price_per_sqft = df.price_per_sqft.str.split('/').str[0].str.split('₹ ').str[1].str.replace(',','').str.strip().astype('float')

In [64]:
df.price_per_sqft

0        20115.0
1       105751.0
2        38251.0
3        43066.0
4        53763.0
5        39062.0
6        37037.0
7        48889.0
8        38150.0
9        10077.0
10       32963.0
11       27778.0
12       34083.0
13       33200.0
14       30556.0
15       14914.0
16       29861.0
17       23333.0
18       41762.0
19       15451.0
20       12938.0
21       38095.0
22       25926.0
23       26235.0
24       38760.0
25       25926.0
26        9374.0
27       13410.0
28       21124.0
29       32593.0
30       24170.0
31       37037.0
32       28490.0
33      122222.0
34       13542.0
35       19097.0
36       48148.0
37       22222.0
38       22222.0
39       33333.0
40       32222.0
41        7290.0
42       27741.0
43       50000.0
44       43534.0
45       45889.0
46       34722.0
47           NaN
48       20690.0
49       29716.0
50       16378.0
51       17284.0
52       37777.0
53       12519.0
54       25562.0
55       27971.0
56       21000.0
57       24500.0
58        7058.0
59        7058.0
60       11250.0
61       23333.0
62       13622.0
63       13909.0
64       20000.0
65       35400.0
66       16058.0
67       16058.0
68       13623.0
69       13910.0
70       13910.0
71       12027.0
72       15700.0
73       19708.0
74       16039.0
75       13331.0
76       11100.0
77       11100.0
78       11100.0
79       40135.0
80       16244.0
81       19708.0
82       16039.0
83       11100.0
84       11100.0
85       16999.0
86       10714.0
87       12027.0
88           NaN
89           NaN
90       21605.0
91       10463.0
92       18750.0
93       19000.0
94       27793.0
95       22006.0
96       19000.0
97       13333.0
98       22222.0
99       28760.0
100      16975.0
101      41615.0
102      16058.0
103      15700.0
104          NaN
105          NaN
106      14444.0
107      10101.0
108      38703.0
109      22222.0
110      12828.0
111      12842.0
112      23148.0
113       8557.0
114      16428.0
115          NaN
116      10556.0
117      13519.0
118      42032.0
119      24069.0
120      21605.0
121      13889.0
122      14650.0
123      13889.0
124      13778.0
125      15625.0
126      23333.0
127      21250.0
128      38667.0
129      26667.0
130      12593.0
131      26389.0
132      12963.0
133      25514.0
134      24845.0
135      17650.0
136      24280.0
137      26423.0
138       6666.0
139       8916.0
140      36667.0
141       9000.0
142      20000.0
143       9028.0
144       4074.0
145        630.0
146      86567.0
147      92857.0
148     100000.0
149      88157.0
150      29974.0
151      24691.0
152       2778.0
153      46906.0
154      25000.0
155      23699.0
156      25960.0
157      28424.0
158      33333.0
159       4490.0
160      14729.0
161      25111.0
162      25000.0
163       7309.0
164      10556.0
165      74074.0
166      12000.0
167      10233.0
168      26852.0
169       8878.0
170      14286.0
171       8928.0
172       8007.0
173      11111.0
174       5698.0
175      28283.0
176      24214.0
177      26613.0
178     138888.0
179      10000.0
180       7666.0
181       7407.0
182       8333.0
183       4666.0
184      13333.0
185      60000.0
186      11111.0
187       7778.0
188      40775.0
189      99173.0
190      12222.0
191       6172.0
192      22222.0
193       9111.0
194      80357.0
195       4117.0
196       7308.0
197       8701.0
198       8000.0
199      25926.0
200       6666.0
201       2296.0
202       8888.0
203      33333.0
204      12444.0
205       9793.0
206       6250.0
207       8486.0
208      11717.0
209       7589.0
210      13333.0
211      12592.0
212      15384.0
213       7843.0
214      22222.0
215      23333.0
216      29336.0
217      10288.0
218      11284.0
219      11029.0
220      10277.0
221       6944.0
222       8518.0
223      10555.0
224      11250.0
225        557.0
226       8888.0
227      11852.0
228       8947.0
229      39265.0
230       6083.0
231     230547.0
232       8411.0
233      32291.0
234      41666.0
235       8889.0
236       7280.0
237      90000.0
238      10089.0
239       8697.0
240       8500.0
241       9333.0
242       8235.0
243      13333.0
244      21667.0
245      20425.0
246       5472.0
247       6944.0
248      57692.0
249      60000.0
250          NaN
251       3857.0
252      21759.0
253       8333.0
254       7407.0
255      75000.0
256      10482.0
257      25386.0
258       8735.0
259       9444.0
262      20000.0
263      18667.0
264      18889.0
265       2525.0
266      24306.0
267      17695.0
268      21519.0
269      17817.0
270          2.0
271       6173.0
272      55000.0
273          NaN
274      13888.0
275      20323.0
276      20359.0
277          NaN
278          NaN
279       5833.0
280      11693.0
281      26667.0
282      53125.0
283      17900.0
284          NaN
285      39886.0
286     126865.0
287      40909.0
288      27155.0
289      14492.0
292      13622.0
293      14045.0
294      10783.0
295      10804.0
296      10783.0
297      14167.0
298      11111.0
299          NaN
300      13157.0
301       5888.0
302      11111.0
303       7875.0
304       9654.0
305       4808.0
306       8222.0
307      11111.0
308       3857.0
309      50000.0
310      11273.0
311       8000.0
312       7627.0
313       5666.0
314       5000.0
315       5000.0
316       6567.0
317      22068.0
318      13333.0
319       6666.0
320      66666.0
321       7500.0
322       8386.0
323      12444.0
324      25000.0
325       6944.0
326          NaN
327      11111.0
328      28674.0
329       9725.0
330      21111.0
331       7500.0
332      10784.0
333      12162.0
334       8910.0
335      10518.0
336      19869.0
337       8796.0
338       9722.0
339       7522.0
340       5658.0
341       5000.0
342      24545.0
343       7701.0
344       8235.0
345      14072.0
346      26000.0
347      24305.0
348      19286.0
349      22634.0
350      26570.0
351      11111.0
352       6410.0
353     133079.0
354      15257.0
356       5778.0
357       6111.0
358      15625.0
359      78125.0
360      17955.0
361       7916.0
362     211111.0
363      80000.0
364      35000.0
365      10000.0
366     120000.0
367      22297.0
368     125000.0
369       8889.0
370      73333.0
371          NaN
372      11111.0
373      26235.0
374       6790.0
375      20833.0
376     315789.0
377      10224.0
378       3500.0
379       3285.0
380      74000.0
381      27139.0
382      10000.0
383       5555.0
385      23662.0
386      17574.0
387      13333.0
388      10753.0
389       9091.0
390      23557.0
391      59259.0
392     105263.0
393      21195.0
394        151.0
395      25103.0
396      13889.0
397      14954.0
398      23333.0
399       8784.0
400       6500.0
401      35494.0
402      11464.0
403      11718.0
404      11555.0
405      50000.0
406       3874.0
407       7576.0
408      11556.0
409      10753.0
410      20635.0
411      10378.0
412      11888.0
413      17284.0
414      32258.0
415      11111.0
416      12222.0
417      16389.0
418      31506.0
419       9722.0
420      12820.0
421     229885.0
422      10000.0
423       8889.0
424      12400.0
425       9259.0
426        232.0
427      15257.0
428     218750.0
429      54794.0
430      14245.0
431       6367.0
432      37313.0
433      90909.0
434       9444.0
435       5000.0
436          NaN
437      10122.0
438      10000.0
439       8642.0
440       6481.0
441       6707.0
442     245398.0
443       9259.0
444          NaN
445      11904.0
446       9135.0
448       7111.0
449       8012.0
450     183333.0
451      12500.0
452      10142.0
453       8444.0
454       8125.0
455      14583.0
456      17037.0
457      11538.0
458       8730.0
459      12222.0
460      14444.0
461      11574.0
462          NaN
463      26667.0
464      11111.0
465       8230.0
466      13095.0
467      30556.0
468      11852.0
469      10000.0
470      29311.0
471      11250.0
472      30384.0
473       8444.0
474      19818.0
475       1992.0
476       7619.0
477      98214.0
478      13499.0
479       7820.0
480       5555.0
481       4000.0
482      14720.0
483       5664.0
484      19753.0
485      76000.0
486      37037.0
487      63492.0
488       9000.0
489       4444.0
490       2500.0
491       6667.0
492       3704.0
493      12777.0
494       6648.0
495      11407.0
496      20233.0
497      17778.0
498      20062.0
499      11494.0
500      25543.0
501      12343.0
502      16892.0
503       8000.0
504      17500.0
505       3904.0
506      14323.0
507       4222.0
508     181818.0
509      75000.0
510      26620.0
511       5555.0
512      10000.0
513       9722.0
514       9500.0
515      17937.0
516       3254.0
517       5333.0
518      30556.0
519       4583.0
520      12500.0
521      21875.0
523      16667.0
524       7075.0
525       8078.0
526       4251.0
527      17584.0
528       5397.0
529       9074.0
530       5583.0
531       3519.0
532      11194.0
533     100000.0
534       6981.0
535       6702.0
536       9444.0
537      10556.0
538      18333.0
539       4877.0
540       7479.0
541       7400.0
542      16003.0
543       8000.0
544       9444.0
545       9103.0
546       7727.0
547      45710.0
549       8702.0
550       5950.0
551       3500.0
552       9722.0
553       8889.0
554      26973.0
555      32407.0
556      13750.0
557       6000.0
558      14890.0
559       9210.0
560       6800.0
561      10518.0
562       7333.0
563       8101.0
564       6944.0
565      14184.0
566       4260.0
567      10582.0
568       9390.0
569      84000.0
570       6938.0
571      15555.0
572      33333.0
573       7539.0
574      10000.0
575      10067.0
576       1649.0
577      10000.0
578      10000.0
579      13000.0
580      28898.0
581      28200.0
582       7168.0
583      20444.0
584          NaN
585      35185.0
586       6289.0
587      17857.0
588       7000.0
589      14166.0
590      30968.0
591       7777.0
592      18658.0
593      10484.0
594     160000.0
595       8127.0
596       5000.0
597       8000.0
598       7555.0
599      49500.0
600       8889.0
601      13030.0
602     308333.0
603       8333.0
604      10610.0
605      18889.0
606       7302.0
607       8155.0
608      10591.0
609      24074.0
610      14815.0
611       5160.0
612     144444.0
613       9615.0
614       9444.0
615      10101.0
616      22222.0
617      32407.0
618       6813.0
619      15046.0
620      11583.0
622       6034.0
623      10085.0
624      17778.0
625      40611.0
626      29630.0
627      29629.0
628      10740.0
629       4444.0
630      17980.0
631      55000.0
632      19737.0
633       5093.0
634      25463.0
635      12000.0
636       7007.0
637       8920.0
638      35294.0
639      12963.0
640       8254.0
641       5128.0
642       5777.0
643      15926.0
644      11111.0
645      14285.0
646      34307.0
647      51864.0
648      44265.0
649      29444.0
650      39074.0
651      38734.0
652      23442.0
653      41833.0
654      27778.0
655     600000.0
656      23889.0
657      25000.0
658      10260.0
659      31915.0
660      11102.0
661       8866.0
662      36911.0
663      36111.0
664      15444.0
665      11240.0
666      15437.0
667      14351.0
668      27191.0
669     241666.0
670      32963.0
671      33592.0
672      24455.0
673      26667.0
674      26389.0
675     194444.0
676      18444.0
677      11600.0
678      38095.0
679      13492.0
680      33951.0
681      11157.0
682       8444.0
683      21495.0
684      42054.0
685       1560.0
686      20741.0
687      13178.0
688      12000.0
689      26428.0
690      82540.0
691      18888.0
692      31481.0
693      13501.0
694      20988.0
695     400000.0
696      21296.0
697      34722.0
698      18626.0
699      24366.0
700      26298.0
701       7500.0
702      24171.0
703      23000.0
704      29697.0
705      33333.0
706      36111.0
707       6778.0
708      22812.0
709     261194.0
710     178571.0
711      27461.0
712      31686.0
713      22222.0
714      23061.0
715      32222.0
716      17662.0
717      39841.0
718      37627.0
719      23148.0
720      29880.0
721      20068.0
722      16569.0
723      21242.0
724      11574.0
725      32562.0
726      13000.0
727      22429.0
728      39530.0
729      22222.0
730      38889.0
731          NaN
732      57206.0
733      27222.0
734      63554.0
735      10601.0
736      20940.0
737      32253.0
738      37037.0
739          NaN
740      23704.0
741      23693.0
742      15989.0
743      19268.0
744      19360.0
745      45833.0
746      29880.0
747      23437.0
748       2716.0
749      39841.0
750      32222.0
751      40850.0
752      12342.0
753      15555.0
754      26111.0
755      31790.0
756      24691.0
757     235376.0
758      29293.0
759      16004.0
760      27333.0
761      17624.0
762      38580.0
763      27778.0
764      35556.0
765      38580.0
766      35000.0
767      30864.0
768          NaN
769     161849.0
770      27778.0
771      16056.0
772      17707.0
785       7718.0
786      25535.0
787       1859.0
788      17037.0
789      10579.0
790      42194.0
791      15625.0
792      15278.0
793     201388.0
794      17187.0
795          NaN
796      44444.0
797      18928.0
798      10926.0
799      19608.0
800       8089.0
801       6849.0
802      24691.0
803          NaN
804      19607.0
805      40000.0
806      34846.0
807      31444.0
808      26235.0
809      22222.0
810      23457.0
811      27083.0
812      43210.0
813      31926.0
814      38611.0
815      27911.0
816      29022.0
817      12837.0
818      12198.0
819      35741.0
820          NaN
821      16666.0
822      35556.0
823       9634.0
825      31481.0
826       7827.0
827      38760.0
828      23556.0
829      10035.0
830      28841.0
831      26615.0
832      24155.0
833      14815.0
834      22222.0
835      62222.0
836       6597.0
837       7870.0
838      26852.0
839      28233.0
840      15111.0
841      34722.0
842      19820.0
843       1087.0
844          NaN
845      31481.0
846      26235.0
847      19645.0
848      36883.0
849      37037.0
850      27871.0
851      35109.0
852      17692.0
853      38022.0
854      33333.0
855      25309.0
856      16990.0
857      14222.0
858      22222.0
859      16388.0
860      22075.0
861      11666.0
862      47167.0
863       7937.0
864      20197.0
865      20635.0
866      34037.0
867      10123.0
868      28858.0
869      28549.0
870      15555.0
871      13513.0
872      20769.0
873      34568.0
874      21097.0
875      33951.0
876      24306.0
877      25556.0
878      36111.0
879       7756.0
880      21825.0
881      12342.0
882      16577.0
883      17706.0
884      29074.0
885      29880.0
886      42222.0
887      38194.0
888      21605.0
889      38194.0
890      37778.0
891      31111.0
892      17213.0
893      18620.0
894      17014.0
895       7750.0
896       7172.0
897      29638.0
898      33333.0
899       8137.0
900       7582.0
901      48148.0
902      18605.0
903      16066.0
904      55556.0
905      38986.0
906      24510.0
907      11428.0
908      22184.0
909      30247.0
910      20370.0
911      31666.0
912      18889.0
913     283333.0
914      31481.0
915      42222.0
916      59259.0
917      45833.0
918      18008.0
919      26235.0
920          NaN
921      33333.0
922      12285.0
923      19293.0
924      20599.0
925     173992.0
926      21367.0
927      20299.0
928      41818.0
929       9634.0
930      19231.0
931      20833.0
932      33333.0
933       6875.0
934      14667.0
935      14787.0
936      16319.0
937      18250.0
938      27390.0
939      30728.0
940      35000.0
941      30556.0
942      41315.0
943       3786.0
944      60000.0
945      24691.0
946       9349.0
947      23504.0
948      21605.0
949     234375.0
950      26235.0
951      21786.0
952      35000.0
953       8235.0
954      15432.0
955      37627.0
956      21251.0
957      30556.0
958      27160.0
959      35530.0
960      22046.0
961      22222.0
962      33333.0
963      27132.0
964      22855.0
965      40741.0
966      34722.0
967      29333.0
968      32328.0
969     290948.0
970      25562.0
971      12393.0
972      22331.0
973      20317.0
974      18088.0
975      21759.0
976      16600.0
977      21219.0
978      19125.0
979      18885.0
980      15000.0
981      37037.0
982      18814.0
983      32328.0
984      23457.0
985      16975.0
986      18889.0
987      14000.0
988      32407.0
989     266666.0
990      26502.0
991      23148.0
992      32407.0
993      33951.0
994      18808.0
995      31481.0
996      10838.0
997      19847.0
998      23148.0
999      12037.0
1000     17820.0
1001     24390.0
1002     35185.0
1003         NaN
1004     26063.0
1005     79365.0
1006     23932.0
1007     24573.0
1008     24005.0
1009     32870.0
1010     33404.0
1011     23240.0
1012     29630.0
1013     16071.0
1014     51440.0
1015     26667.0
1016     28782.0
1017     34491.0
1018     34351.0
1019     47803.0
1020      6230.0
1021     33665.0
1022     44444.0
1023         NaN
1024         NaN
1025     20566.0
1026     22222.0
1027     26667.0
1028     20349.0
1029     23148.0
1030     21124.0
1031     24202.0
1032     24155.0
1033     23870.0
1034     24500.0
1035     24845.0
1036     20026.0
1037     28787.0
1038     12551.0
1039     30556.0
1040     31481.0
1041     33333.0
1042     33129.0
1043     14815.0
Name: price_per_sqft, dtype: float64

In [65]:
# bedrooms
df.bedRoom.value_counts()

bedRoom
4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [67]:
df.bedRoom.isnull().sum()

57

In [68]:
df[df.bedRoom.isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
62,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
63,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13909.0,(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
66,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
67,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
68,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13623.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
69,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(294-418 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
70,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
71,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
72,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
73,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
74,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
75,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13331.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
76,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
77,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
78,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
81,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
82,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
83,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(325 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
84,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
85,4 Bedroom House for sale in Sector 23 Gurgaon,all punjabi welfare association,NaN,16999.0,(139-279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 23 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['HUDA Sector 23 Market', 'Palam triangle', 'R...",All punjabi welfare association in sector-23 g...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
86,4 Bedroom House for sale in Sector 72 Gurgaon,tata primanti,NaN,10714.0,(650-790 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 72 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Tata primanti in sector-72, gurgaon by tata ho...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4.5 out ..."
87,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
88,5 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(251-704 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
89,3 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(211 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
92,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,18750.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
93,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
94,5 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,27793.0,(571-711 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
95,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,22006.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
96,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
97,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13333.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
98,5 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,22222.0,(293-381 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
99,4 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,28760.0,(207 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
100,3 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,16975.0,(301 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
102,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
103,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
104,4 Bedroom House for sale in Sector 65 Gurgaon,emaar emerald hills,NaN,NaN,(183 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 65 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Emerald Plaza Shopping Mall', 'Southern Peri...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
105,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
110,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12828.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
111,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12842.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
115,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,NaN,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
273,5 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,NaN,NaN,(509-543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Metro Station Kankrola sec 87', 'Sapphire 83...","Bestech park view ananda in sector-81 gurgaon,...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
277,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
278,6 Bedroom House for sale in Sector 70 Gurgaon,tulip ivory,NaN,NaN,(697 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 70 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Reach 3 Roads Shopping Mall', 'Southern Peri...","Tulip ivory in sector-70, gurgaon by tulip inf...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
284,3 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf the palm drive,NaN,NaN,(353 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf the palm drive in sector-66, gurgaon...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
292,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(540 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
293,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,14045.0,(363 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
294,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10783.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
295,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10804.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
296,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10783.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
318,3 Bedroom House for sale in Arjun Nagar,independent,NaN,13333.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,2 Bedroom House for sale in Palam Vihar Extension,independent,NaN,6666.0,(49 sq.m.) Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,2 Bedroom House for sale in Rajiv Nagar,independent,NaN,66666.0,(7 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,7 Bedroom House for sale in Surya Vihar,independent,NaN,7500.0,(372 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,2 Bedroom House for sale in Sector 5 Gurgaon,independent,NaN,25000.0,(93 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,4 Bedroom House for sale in Sohna,independent,NaN,6944.0,(167 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,4 Bedroom House for sale in Sector 52 Gurgaon,independent,NaN,NaN,(201 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,6 Bedroom House for sale in Sector 22 Gurgaon,saksham welfare association,NaN,19645.0,(220 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df = df[~df['bedRoom'].isnull()]

In [70]:
df.shape

(964, 19)

In [71]:
df.bedRoom = df.bedRoom.str.split().str[0]

C:\Users\vinay\AppData\Local\Temp\ipykernel_11536\992969072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.bedRoom = df.bedRoom.str.split().str[0]

In [72]:
df.bathroom.value_counts()

bathroom
4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
18 Bathrooms      4
13 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [73]:
df.bathroom.isnull().sum()

0

In [75]:
df.bathroom.str.split().str[0].value_counts()

bathroom
4     228
3     165
5     137
2     114
6      82
1      65
9      42
7      39
8      28
12     22
10     11
16      8
18      4
13      4
11      4
20      3
17      3
14      2
21      1
36      1
34      1
Name: count, dtype: int64

In [76]:
df.bathroom = df.bathroom.str.split().str[0]

In [77]:
# balcony 
df.balcony.value_counts()

balcony
3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: count, dtype: int64

In [81]:
df.balcony.str.replace('No' , '0').str.split().str[0].value_counts()

balcony
3+    365
2     220
3     159
0     115
1     105
Name: count, dtype: int64

In [82]:
df.balcony = df.balcony.str.replace('No' , '0').str.split().str[0]

In [83]:
# additionalRoom
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Store Room,Study Room,Servant Room     8
Pooja Room,Servant Room,Store Room                7
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Servant Room,Pooja Room,Store Room                6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Pooja Room,Servant Room                5
Servant Room,Store Room,Pooja Room                4
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [84]:
df['additionalRoom'].fillna('not available',inplace=True)

In [85]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [86]:
# floors
df['noOfFloor'].value_counts()

noOfFloor
3 Floors     304
2 Floors     288
1 Floors     181
4 Floors     136
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: count, dtype: int64

In [87]:
df.noOfFloor.isnull().sum()

19

In [89]:
df.noOfFloor = df.noOfFloor.str.split().str[0]

In [90]:
df.noOfFloor.dtype

dtype('O')

In [91]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [92]:
df.facing.fillna('NA' , inplace = True)

In [93]:
df.facing.value_counts()

facing
NA            303
East          178
North-East    158
North         109
West           75
North-West     44
South-East     39
South          34
South-West     24
Name: count, dtype: int64

In [94]:
df.insert(loc=1,column='property_type',value='house')

In [96]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [97]:
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

In [98]:
df.shape

(964, 20)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 1043
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    object
 8   bathroom         964 non-null    object
 9   balcony          964 non-null    object
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    object
 13  facing           964 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
dtypes: float64(3), object(17)
memory usage: 158.2+ KB

In [100]:
df.to_csv('cleaned_house.csv',index=False)